import {useState,type FormEvent} from 'react';
import {Navigate,useNavigate} from 'react-router-dom';
import {useAuth} from '../lib/auth';
import {db,errorText,supabase} from '../lib/supabase';
export function Login(){
 const {profile,session,error:profileError,reload}=useAuth();const [mode,setMode]=useState<'login'|'forgot'>('login');const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 if(profile)return <Navigate to={profile.role==='staff'?'/my-schedule':'/overview'} replace/>;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');const form=new FormData(e.currentTarget);
  try{if(mode==='forgot'){const {error}=await db().auth.resetPasswordForEmail(String(form.get('email')),{redirectTo:window.location.origin+'/recovery'});if(error)throw error;setMessage('Jika email terdaftar, tautan pemulihan akan dikirim.');}
   else{const {error}=await db().auth.signInWithPassword({email:String(form.get('email')),password:String(form.get('password'))});if(error)throw error;await reload();}}
  catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <div className="auth-page"><div className="auth-brand"><div className="logo">O</div><h1>Orbiz Ops</h1><p>Operator Management</p><div className="brand-rule"/><p>Jakarta & Bandung</p></div><main className="auth-card"><p className="eyebrow">WORKSPACE INTERNAL</p><h2>{mode==='login'?'Masuk ke workspace':'Pulihkan password'}</h2><p className="muted">Gunakan akun yang diundang oleh administrator.</p>{!supabase?<div role="alert" className="notice">Koneksi aplikasi belum dikonfigurasi. Administrator perlu menyelesaikan setup Supabase.</div>:<form onSubmit={submit}><label>Email<input name="email" type="email" autoComplete="email" required/></label>{mode==='login'&&<label>Password<input name="password" type="password" autoComplete="current-password" required/></label>}<button className="primary" disabled={busy}>{busy?'Memproses…':mode==='login'?'Masuk':'Kirim tautan pemulihan'}</button></form>}{(error||profileError)&&<div className="notice error" role="alert">{error||profileError}</div>}{message&&<div className="notice success" role="status">{message}</div>}{session&&!profile&&<button onClick={()=>void db().auth.signOut()}>Keluar dari akun</button>}<button className="text-button" onClick={()=>{setMode(mode==='login'?'forgot':'login');setError('');setMessage('');}}>{mode==='login'?'Lupa password?':'Kembali ke login'}</button></main></div>;
}
export function Recovery(){const [busy,setBusy]=useState(false),[error,setError]=useState('');const {session,reload}=useAuth();const navigate=useNavigate();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('confirm')){setError('Password belum sama');return;}setBusy(true);try{const {error}=await db().auth.updateUser({password:String(f.get('password'))});if(error)throw error;await reload();navigate('/login',{replace:true});}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <main className="auth-card standalone"><h1>Atur password</h1>{session?<form onSubmit={submit}><label>Password baru<input name="password" type="password" minLength={12} autoComplete="new-password" required/></label><label>Ulangi password<input name="confirm" type="password" minLength={12} autoComplete="new-password" required/></label><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan password'}</button></form>:<p>Tautan tidak valid atau kedaluwarsa. Minta tautan baru dari halaman login.</p>}{error&&<p role="alert">{error}</p>}<button onClick={()=>navigate('/login')}>Kembali</button></main>;
}
