import {useEffect,useState} from 'react';
import {db} from '../lib/supabase';
import {addDays,hourLabel,monday,prettyDate,ranges,slotAllowed} from '../lib/domain';
import {checked,type Context} from './Workspace';
type Preview={valid:number;existing:number;skipped:{operator_id:string;date:string;hour:number;reason:string}[]};
export function Plotting(c:Context){
 const {data,location,start,end,busy,run}=c;const [selected,setSelected]=useState(''),[anchor,setAnchor]=useState<{operator:string;date:string;hour:number}|null>(null);
 const [source,setSource]=useState(start),[targetText,setTargetText]=useState(''),[mode,setMode]=useState('merge'),[preview,setPreview]=useState<Preview|null>(null);
 const [pubWeek,setPubWeek]=useState(monday(start));const operators=data.profiles.filter(p=>p.role==='staff');
 useEffect(()=>{setAnchor(null);setPreview(null);setSource(start);setPubWeek(monday(start));},[start,end,location]);
 const name=(id:string)=>operators.find(o=>o.id===id)?.display_name??id;
 async function pick(op:string,date:string,hour:number){
  if(!op)return;
  if(!anchor){if(!slotAllowed(op,date,hour,data.slots,data.leaves)){await run('',async()=>{throw new Error('Jam mulai belum memiliki availability approved atau terkena izin.');});return;}setAnchor({operator:op,date,hour});return;}
  if(anchor.operator!==op||anchor.date!==date)return;
  const a=Math.min(anchor.hour,hour),b=Math.max(anchor.hour,hour)+1;
  if(Array.from({length:b-a},(_,i)=>a+i).some(h=>!slotAllowed(op,date,h,data.slots,data.leaves))){await run('',async()=>{throw new Error('Seluruh rentang harus memiliki availability approved dan bebas izin.');});return;}
  const ok=await run('Draft tersimpan',async()=>checked(await db().rpc('upsert_operator_assignment',{p_operator:op,p_location:location,p_date:date,p_start:a,p_end:b})));
  if(ok)setAnchor(null);
 }
 const targets=()=>[...new Set(targetText.split(/[\s,]+/).filter(Boolean))];
 async function copy(isPreview:boolean){
  if(targets().some(t=>!/^\d{4}-\d{2}-\d{2}$/.test(t)))return void run('',async()=>{throw new Error('Tanggal tujuan harus YYYY-MM-DD, dipisahkan koma.');});
  await run(isPreview?'Preview copy diperbarui':'Pola jadwal disalin',async()=>{const result=await checked(await db().rpc('copy_schedule_day',{p_location:location,p_source:source,p_targets:targets(),p_mode:mode,p_preview:isPreview}));setPreview(result as unknown as Preview);},isPreview?undefined:mode==='replace'?'Ganti seluruh draft pada tanggal tujuan? Slot sumber yang tidak valid akan dilewati. Jadwal published tetap sampai publikasi berikutnya.':'Salin slot valid ke draft tanggal tujuan?');
 }
 const count=Math.round((Date.parse(end)-Date.parse(start))/86400000)+1;
 return <><div className="notice">Tarik nama ke jam mulai, lalu klik kotak jam terakhir pada baris yang sama. Di ponsel, pilih operator lalu ketuk jam mulai dan terakhir.</div><div className="toolbar"><label>Operator<select value={selected} onChange={e=>{setSelected(e.target.value);setAnchor(null);}}><option value="">Pilih operator</option>{operators.filter(o=>o.active).map(o=><option value={o.id} key={o.id}>{o.display_name}</option>)}</select></label><label>Minggu publikasi (Senin)<input type="date" value={pubWeek} onChange={e=>setPubWeek(e.target.value)}/></label><button className="primary" disabled={busy||!pubWeek} onClick={()=>void run('Jadwal dipublikasikan',async()=>checked(await db().rpc('publish_schedule_week',{p_location:location,p_week:pubWeek})),`Publikasikan draft ${prettyDate(pubWeek)} sampai ${prettyDate(addDays(pubWeek,6))}? Jadwal published minggu ini akan diganti, termasuk jika draft kosong.`)}>Publikasikan minggu</button></div>{anchor&&<div className="notice">{name(anchor.operator)} mulai {hourLabel(anchor.hour)} · pilih jam terakhir. <button onClick={()=>setAnchor(null)}>Batalkan pilihan</button></div>}<div className="plot-layout"><div className="card pool"><h2>Operator</h2>{operators.filter(o=>o.active).map(o=><button disabled={busy} draggable={!busy} onDragStart={e=>{e.dataTransfer.setData('text/plain',o.id);setSelected(o.id);}} onClick={()=>{setSelected(o.id);setAnchor(null);}} className={selected===o.id?'selected':''} key={o.id}><strong>{o.display_name}</strong><small>{data.slots.filter(s=>s.operator_id===o.id&&s.status==='approved').length} jam available</small></button>)}{!operators.length&&<p className="muted">Belum ada operator.</p>}</div><section className="card board"><div className="timeline"><div className="bands"><b>KATEGORI JAM</b><span>Midnight · 00–08</span><span>Pagi · 08–12</span><span>Siang · 12–16</span><span>Malam · 16–24</span></div><div className="hour-row header-row"><b>Nama operator</b>{Array.from({length:24},(_,h)=><span key={h}>{String(h).padStart(2,'0')}</span>)}</div>{Array.from({length:Math.min(count,31)},(_,i)=>addDays(start,i)).map(date=>{
 const rows=data.assignments.filter(a=>a.work_date===date);const opIds=[...new Set([...rows.map(a=>a.operator_id),...(anchor?.date===date?[anchor.operator]:[])])];
 const row=(op:string)=>{const hours=rows.filter(a=>a.operator_id===op).map(a=>a.hour);return <div className="operator-block" key={op||'new'}><div className="hour-row"><div className="operator-name"><strong>{op?name(op):'Tambah jadwal'}</strong><small>{op?ranges(hours).map(r=>hourLabel(r.start)+'–'+hourLabel(r.end)).join(' · '):'Tarik nama / pilih operator'}</small></div>{Array.from({length:24},(_,h)=>{const active=hours.includes(h),targetOp=op||selected,available=slotAllowed(targetOp,date,h,data.slots,data.leaves),pending=anchor?.date===date&&anchor.operator===op&&anchor.hour===h;return <button key={h} disabled={busy} aria-label={`${op?name(op):'Tambah'} ${date} ${hourLabel(h)}${active?' terisi':''}`} title={active?'Jam terisi':available?'Available approved':'Belum tersedia'} className={`hour ${active?'filled':''} ${pending?'pending':''} ${available?'available':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(operators.some(o=>o.id===id&&o.active)&&(!op||op===id)){setAnchor(null);setSelected(id);if(slotAllowed(id,date,h,data.slots,data.leaves))setAnchor({operator:id,date,hour:h});else void run('',async()=>{throw new Error('Jam mulai tidak tersedia');});}}} onClick={()=>void pick(targetOp,date,h)}>{active?'•':pending?'↓':''}</button>;})}</div>{op&&hours.length>0&&<div className="range-actions">{ranges(hours).map(r=><button key={r.start} disabled={busy} onClick={()=>void run('Rentang draft dihapus',async()=>checked(await db().rpc('upsert_operator_assignment',{p_operator:op,p_location:location,p_date:date,p_start:r.start,p_end:r.end,p_remove:true})),`Hapus ${name(op)} ${hourLabel(r.start)}–${hourLabel(r.end)} dari draft?`)}>Hapus {hourLabel(r.start)}–{hourLabel(r.end)}</button>)}</div>}</div>;};
 return <div key={date}><div className="date-divider"><strong>{prettyDate(date)}</strong><span>{opIds.length} operator</span></div>{opIds.map(row)}{row('')}</div>;
 })}</div>{count>31&&<div className="notice">Timeline menampilkan 31 hari pertama. Persempit filter untuk hari selanjutnya.</div>}</section></div><section className="card"><h2>Copy pola jadwal</h2><div className="form-grid"><label>Hari sumber<input type="date" value={source} onChange={e=>{setSource(e.target.value);setPreview(null);}}/></label><label>Tanggal tujuan (pisahkan koma)<input placeholder="2026-09-15, 2026-09-16" value={targetText} onChange={e=>{setTargetText(e.target.value);setPreview(null);}}/></label><label>Mode<select value={mode} onChange={e=>{setMode(e.target.value);setPreview(null);}}><option value="merge">Gabungkan</option><option value="replace">Ganti draft tujuan</option></select></label></div><div className="toolbar"><button disabled={busy||!targetText} onClick={()=>void copy(true)}>Preview copy</button><button className="primary" disabled={busy||!preview} onClick={()=>void copy(false)}>Terapkan copy</button></div>{preview&&<><p><strong>{preview.valid}</strong> jam valid · {preview.existing} jam sudah ada · {preview.skipped.length} jam dilewati</p><p className="muted">Validasi diulang saat diterapkan; hasil dapat berubah jika ada approval atau perubahan jadwal.</p>{preview.skipped.length>0&&<div className="table-wrap"><table><thead><tr><th>Operator</th><th>Tanggal</th><th>Jam</th><th>Alasan</th></tr></thead><tbody>{preview.skipped.map((s,i)=><tr key={i}><td>{name(s.operator_id)}</td><td>{s.date}</td><td>{hourLabel(s.hour)}</td><td>{s.reason}</td></tr>)}</tbody></table></div>}</>}</section></>;
}
