import {useEffect,useState} from 'react';
import {db,errorText} from '../lib/supabase';
import {groupAssignments,hourLabel,logbookPeriod,money,prettyDate,type Cost} from '../lib/domain';
import {exportLogbook} from '../lib/export';
import {checked,Metric,type Context} from './Workspace';
export function CostReport(c:Context){const {location,start,end,data,busy,profile,setDateRange}=c;const [all,setAll]=useState(false),[rows,setRows]=useState<Cost[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;setRows([]);setLoading(true);setError('');void(async()=>{try{const value=await checked(await db().rpc('calculate_operator_cost',{p_location:all&&profile.role==='super_admin'?null:location,p_start:start,p_end:end}));if(!cancelled)setRows(value as unknown as Cost[]);}catch(e){if(!cancelled)setError(errorText(e));}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[location,start,end,all,data.assignments,profile.role]);
 return <><div className="toolbar">{profile.role==='super_admin'&&<label className="inline"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Gabungkan Jakarta & Bandung</label>}<button disabled={busy} title="21 bulan sebelumnya sampai 20 bulan berjalan" onClick={()=>{const period=logbookPeriod(start);setDateRange(period.start,period.end);}}>Periode Mitra 21–20</button></div><div className="notice">Estimasi dari jam published yang masih aktif. Fee mengikuti histori effective date dan snapshot publikasi. Ini bukan perhitungan payroll final atau absensi aktual.</div>{error&&<div className="notice error" role="alert">{error}</div>}{loading?<p role="status">Menghitung cost…</p>:<><div className="metrics"><Metric label="Operator" value={rows.length}/><Metric label="Hari jaga (per operator)" value={rows.reduce((s,r)=>s+r.working_days,0)}/><Metric label="Total jam" value={rows.reduce((s,r)=>s+r.total_hours,0)}/><Metric label="Estimasi salary" value={money(rows.reduce((s,r)=>s+r.estimated_salary,0))}/></div><section className="card"><h2>Rincian cost operator</h2><div className="table-wrap"><table><thead><tr><th>Operator</th><th>Lokasi</th><th>Hari jaga</th><th>Jam</th><th>Rate yang digunakan</th><th>Estimasi salary</th></tr></thead><tbody>{rows.map(r=><tr key={r.operator_id}><td>{r.display_name}</td><td>{r.location_id}</td><td>{r.working_days}</td><td>{r.total_hours}</td><td>{r.applicable_rates.map(rate=>money(rate.hourly_fee)).join(' · ')} / jam</td><td><strong>{money(r.estimated_salary)}</strong></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Belum ada jam published pada periode ini.</p>}</div></section></>}</>;
}
export function PersonalSchedule(c:Context){const {data,profile,start,end,busy,run}=c;const [colleagues,setColleagues]=useState<{work_date:string;hour:number;display_name:string}[]>([]),[error,setError]=useState(''),[loadingColleagues,setLoadingColleagues]=useState(true);
 useEffect(()=>{let disposed=false;setColleagues([]);setError('');setLoadingColleagues(true);void(async()=>{try{const value=await checked(await db().rpc('get_overlapping_colleagues',{p_start:start,p_end:end}));if(!disposed)setColleagues(value??[]);}catch(e){if(!disposed)setError(errorText(e));}finally{if(!disposed)setLoadingColleagues(false);}})();return()=>{disposed=true;};},[start,end,data.assignments]);
 return <><div className="metrics"><Metric label="Hari terjadwal" value={new Set(data.assignments.map(a=>a.work_date)).size}/><Metric label="Total jam" value={data.assignments.length}/></div><section className="card"><div className="section-head"><h2>Jadwal published</h2><button className="primary" disabled={busy||!data.assignments.length} onClick={()=>void run('Logbook .xlsx siap diunduh',()=>exportLogbook(profile,start,end))}>Export .xlsx untuk HR</button></div>{error&&<div className="notice error" role="alert">Nama rekan satu shift belum dapat dimuat: {error}</div>}{!data.assignments.length?<p className="empty">Belum ada jadwal published dalam rentang ini.</p>:<div className="schedule-list">{groupAssignments(data.assignments).map(g=><article key={g.date}><h3>{prettyDate(g.date)}</h3>{g.ranges.map(r=>{const names=[...new Set(colleagues.filter(co=>co.work_date===g.date&&co.hour>=r.start&&co.hour<r.end).map(co=>co.display_name))];return <div className="personal-range" key={r.start}><strong>{hourLabel(r.start)}–{hourLabel(r.end)}</strong><span>{r.end-r.start} jam jaga</span><div className="shift-colleagues"><small>REKAN SATU SHIFT</small><strong>{loadingColleagues?'Memuat…':names.join(', ')||'Tidak ada rekan yang overlap'}</strong></div></div>;})}</article>)}</div>}</section></>;
}
